### ISSUE TITLE
error: db type could not be determined

### ISSUE THREAD

**Issue by bipinu** [rollbar/rollbar-agent#16]
I installed using pip, and symlinked the config and shell script.
I encounter the following error when I start the rollbar service: 

2014-08-03 18:24:11,566 ERROR Caught exception in ScannerThread.run() loop
Traceback (most recent call last):
  File "/usr/local/rollbar-agent", line 428, in run
    self.scan_all()
  File "/usr/local/rollbar-agent", line 444, in scan_all
    state = self.load_state()
  File "/usr/local/rollbar-agent", line 463, in load_state
    flag='n' if recreate else 'c')
  File "/usr/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python2.7/shelve.py", line 223, in **init**
    Shelf.**init**(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python2.7/anydbm.py", line 82, in open
    raise error, "db type could not be determined"
error: db type could not be determined
2014-08-03 18:24:18,516 INFO  Shutting down...
2014-08-03 18:24:19,517 INFO  Shutdown complete

**Comment by rivkahstandig3636** [comment]
Is this still an issue?

**Comment by jessewgibbs** [comment]
@rivkahstandig3636 I can't find this user anywhere in our system and he's not responded in over 3 weeks, so I'm going to close this issue.
