### ISSUE TITLE
ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))

### ISSUE THREAD

**Issue by barrycarrjr** [rollbar/rollbar-agent#44]
Out of no where we began getting the error below

2018-10-10 21:14:53,004 ERROR Caught exception in ScannerThread.scan_all() loop
Traceback (most recent call last):
File "/usr/local/rollbar-agent", line 468, in scan_all
self.scan_app(app, apps_state)
File "/usr/local/rollbar-agent", line 532, in scan_app
self.scan_file(app, filename, files_state[filename])
File "/usr/local/rollbar-agent", line 546, in scan_file
processor.process(fp, filename, file_state)
File "/usr/local/rollbar-agent", line 240, in process
self._process_line(line)
File "/usr/local/rollbar-agent", line 259, in _process_line
self.send_payload(line)
File "/usr/local/rollbar-agent", line 226, in send_payload
headers={"content-type": "application/json"})
File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))

**Comment by jessewgibbs** [comment]
Hey Barry,

Sorry to hear you're encountering this issue.  Did this error happen just once or repeatedly?  And have you tried restarting the agent?

**Comment by barrycarrjr** [comment]
It was occurring repeatedly for a while. Yes, I restarted the agent but it kept occurring, so I had to turn off the agent. The agent is back on now and the error is not occurring at this time.

 

 

 

 

 

Barry L. Carr

The M3 Media Group

Tel. 215.463.6348 x9200
Fax. 530.869.7077 |  <mailto:barry.c@them3mediagroup.com> barry.c@them3mediagroup.com |  <http://www.them3mediagroup.com> www.them3mediagroup.com

**Comment by jessewgibbs** [comment]
Thanks, Barry, for the update.  Glad to hear that this is now working.  I'm going to keep this issue open in our backlog as an enhancement to make the messages more informative when there is some kind of IO issue.

**Comment by anuj-reef** [comment]
@jessewgibbs I am getting the same error and restarting the agent did not work.

**Comment by jessewgibbs** [comment]
@anuj-reef sorry to hear that you're encountering this problem.

Can you let us know:

- OS version
- Python version
- Any other info that might help us to reproduce the problem

**Comment by srikiraju** [comment]
Agreed. `rollbar-agent` should just handle this case transparently

**Comment by levesquejf** [comment]
Any updates on this bug? I have a similar issue right now. It's hard to debug when I can not catch my Python Exceptions...
